#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

#include "../bibliotecas/heapmax.h"

/*GENERATED BY CLAUDE AI*/

void test_criar() {
    printf("\nTest 1: Testing heap creation\n");
    printf("-----------------------------\n");
    
    HEAPMAX *heap = heapmax_criar();
    if (heap != NULL) {
        printf("✓ Heap created successfully\n");
        printf("✓ Initial size: %d\n", heapmax_tamanho(heap));
        printf("✓ Is empty: %s\n", heapmax_vazia(heap) ? "true" : "false");
    } else {
        printf("✗ Failed to create heap\n");
    }
    
    heapmax_apagar(&heap);
}

void test_insercao() {
    printf("\nTest 2: Testing insertion\n");
    printf("-------------------------\n");
    
    HEAPMAX *heap = heapmax_criar();
    int elements[] = {4, 10, 3, 5, 1, 8, 2, 7, 6, 9};
    int num_elements = sizeof(elements) / sizeof(elements[0]);
    
    printf("Inserting elements: ");
    for (int i = 0; i < num_elements; i++) {
        printf("%d ", elements[i]);
    }
    printf("\n\n");
    
    for (int i = 0; i < num_elements; i++) {
        if (heapmax_inserir(heap, elements[i])) {
            printf("After inserting %d (size: %d): ", elements[i], heapmax_tamanho(heap));
            heapmax_imprimir(heap);
        }
    }
    
    heapmax_apagar(&heap);
}

void test_heapsort() {
    printf("\nTest 3: Testing HeapSort\n");
    printf("-----------------------\n");
    
    HEAPMAX *heap = heapmax_criar();
    int elements[] = {4, 10, 3, 5, 1, 8, 2, 7, 6, 9};
    int num_elements = sizeof(elements) / sizeof(elements[0]);
    
    for (int i = 0; i < num_elements; i++) {
        heapmax_inserir(heap, elements[i]);
    }
    
    printf("Before HeapSort: ");
    heapmax_imprimir(heap);
    
    heapSort(heap, heapmax_tamanho(heap));
    printf("After HeapSort:  ");
    heapmax_imprimir(heap);
    
    heapmax_apagar(&heap);
}

void test_busca_binaria() {
    printf("\nTest 4: Testing Binary Search\n");
    printf("----------------------------\n");
    
    HEAPMAX *heap = heapmax_criar();
    int elements[] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}; // Using sorted array for binary search
    int num_elements = sizeof(elements) / sizeof(elements[0]);
    
    // Insert sorted elements
    for (int i = 0; i < num_elements; i++) {
        heapmax_inserir(heap, elements[i]);
    }
    
    // Test cases for binary search
    int test_values[] = {1, 5, 10, 0, 11};
    int num_tests = sizeof(test_values) / sizeof(test_values[0]);
    
    heapSort(heap, heapmax_tamanho(heap));
    printf("Current heap: ");
    heapmax_imprimir(heap);
    
    for (int i = 0; i < num_tests; i++) {
        int result = buscaBinaria(heap, 0, heapmax_tamanho(heap) - 1, test_values[i]);
        if (result != ERRO) {
            printf("Found %d at position %d\n", test_values[i], result);
        } else {
            printf("Element %d not found\n", test_values[i]);
        }
    }
    
    heapmax_apagar(&heap);
}

void test_edge_cases() {
    printf("\nTest 5: Testing Edge Cases\n");
    printf("-------------------------\n");
    
    // Test NULL heap operations
    printf("Testing NULL heap operations:\n");
    heapmax_inserir(NULL, 1);
    heapmax_rearranjar(NULL, 0, 1);
    heapmax_imprimir(NULL);
    heapmax_tamanho(NULL);
    buscaBinaria(NULL, 0, 0, 1);
    
    // Test empty heap operations
    HEAPMAX *empty_heap = heapmax_criar();
    printf("\nTesting empty heap operations:\n");
    heapmax_imprimir(empty_heap);
    heapSort(empty_heap, 0);
    buscaBinaria(empty_heap, 0, 0, 1);
    
    // Test heap full condition
    printf("\nTesting heap full condition:\n");
    for (int i = 0; i < TAM_MAX + 1; i++) {
        if (!heapmax_inserir(empty_heap, i)) {
            printf("Successfully detected full heap at %d elements\n", i);
            break;
        }
    }
    
    heapmax_apagar(&empty_heap);
}

int main() {
    printf("Heap Max ADT Comprehensive Test Suite\n");
    printf("====================================\n");
    
    test_criar();
    test_insercao();
    test_heapsort();
    test_busca_binaria();
    test_edge_cases();
    
    printf("\nTest suite completed.\n");
    return 0;
}